### ISSUE TITLE
Unable to run PAC commands

### ISSUE THREAD

**Issue by ajeyng** [microsoft/PowerPlatform-Catalog#14]
**Describe the bug**
I am trying to install Catalog in my environment which I was able to do so from the Market place. However, I cannot run any PAC Catalog commands. "pac catalog list" returns the following error:

_Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id: 99886f91-45d9-4a3e-af28-7eef767e90c2, Exception Type: System.ArgumentException_
[pac-log.txt](https://github.com/microsoft/PowerPlatform-Catalog/files/13428746/pac-log.txt)

Also, I currently only see Power Platform Catalog Manager App. 

![image](https://github.com/microsoft/PowerPlatform-Catalog/assets/107418214/4d03ccb9-c126-4445-b2aa-c990b35b7d52)

Please help! Thank you. 

**To Reproduce**
Tells us how you got to this behavior:

**Screenshots**

**App Info (please complete the following information):**
 - OS: [e.g. iOS, Windows, Linux]
 - Version [e.g. 1.0.1.16]

**Additional context**

**Comment by MattB-msft** [comment]
Please update to latest CLI.. 

Pac install latest
